---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: monitoring
  interval: 1m0s
  values:
    admissionWebhooks.certManager.autoGenerateCert.enabled: true
    admissionWebhooks.certManager.enabled: false
    manager.featureGates: operator.autoinstrumentation.go
