---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kbot
  namespace: kbot
spec:
  encryptedData:
    token: AgCHrbEfOB2unmUOqf42YA6npHTry+WBXPJCNAxEarHctVbDghagw0/8gRlbOqLxbnooNpT5CrtaRetR15V5KdK65gRQbpSdTfqvlO3wWMpi4lFmO22E/uWTFEj2Q1eGuSFIOtgf68ljjNA3ifp3Aio4Kd9eRKV1Y/B4dUXH6rLHk3USYVEFY26TY5iFaKHPvIKMGAxT5CCU7riJdxb0CdVGFfSjBr+T0Nb93vqQiZu2QcyhAXu5Yu73q+AMlP7y8UbSkDrIFodo9qlWaztDd3uYwIJD6z95yZr5PkjCAnrFMXlOk3Zwj+X3ECJNoLyN5vXkH5PGdX6ze7L4vDEfDtpMRDuu5WvIDR1J3/4J256haNZDLjW8PYFe8ixVq9NIvVpPpmlOUrDDrQU5zEGQtdFmGYCK14paovrAyFsTOGkKWBMPEB3PFV6km7CyMygK6p5YbiUhkiVcdYXPdwc1V52D8GjTbIGPmmdGVrQt+AjTJJTD/AkI9/pdW/Zs2iCj25uQXw3mWIWJYo7uk6T/Rxu3leqg3pE931ESNXvyw5z7ocWRQwcVlYGHguiz2a3Iluedcb34scQuE3FD6Gs3MM72JAXZxPkos49usdWhot4IydZOxiWq9qJzRicU6KOGWek9Esrh5o8jeCumdV6PuhQ2+U8eYHR+kL6XsaW9H0BnkCKdfXFfDOGerIYbOm+u9wtlXa0rZ3mdxlEns9qG60FRdYvBkO+g1pUReQsI6TDfvHCVVEPd+G5U9EF7Jitz
  template:
    metadata:
      creationTimestamp: null
      name: kbot
      namespace: kbot
